#Information that goes into the header of each files

odd: true
dephasing: true
dephasing_param: 0.0
excitation: false
excitation_param: 0.0
relaxation: false
relaxation_param: 0.0
preparation_error: true
