#Information that goes into the header of each files


odd: true
dephasing: True
dephasing_param: 0.3703703703703704 #strong dephasing
excitation: false
excitation_param: 0.0
relaxation: false
relaxation_param: 0.0
preparation_error: false
qubit_displacement_error: False
qubit_displacement_radius: 6e-9
qubit_displacement_halfheight: 3e-9
folder: 'circ_height_var_tau/D_200'


