#Information that goes into the header of each files
odd: false
dephasing: false
dephasing_param: 3240.2200334542995 #strong dephasing
excitation: false
excitation_param: 0.0
relaxation: false
relaxation_param: 0.0
preparation_error: false
qubit_displacement_error: false 
qubit_displacement_radius: 0.0
qubit_displacement_halfheight: 0.0
folder: 'dephasing'
runs: 1