#Information that goes into the header of each files

#odd: false
#dephasing: false
#dephasing_param: 0.0
#excitation: false
#excitation_param: 0.0
#relaxation: false
#relaxation_param: 0.0
#preparation_error: false
#qubit_displacement_error: false 
#qubit_displacement_radius: 0.0
#qubit_displacement_halfheight: 0.0
bit_errors: [0,0,1,0]
displacement: [[1e-9,0,0],[1e-9,0,0],[1e-9,0,0],[1e-9,0,0]]
folder: 'twirl'
subfolder: 'test_sim' # memorable simulation name
runs: 1
